### ISSUE TITLE
[help] Help me download the correct version

### ISSUE THREAD

**Issue by shikulja** [barncastle/Battle.Net-Installer#11]
Requires wow classic _1.14.0_
when downloading with the command:
`BNetInstaller --prod wow_classic_era --lang xxXX --dir xxXX`
i get _1.14.2_

and need 2.5.2 (BCC) but i get last 2.5.4 with --prod wow_classic

I did not find TACT keys for certain versions of old clients.

**Comment by barncastle** [comment]
Unfortunately you cannot access old client versions only the current ones. This acts as an alternate to the Battle.Net app so serves the same clients that does. The advantage of using this application is that you can access content that is hidden in the official app. 

You can find a list of client version per product at https://wow.tools. 

If you need a specific version, your best bet would be reaching out to the wow modding community and see if someone there has a copy of it.
