### ISSUE TITLE
1.4v error 2421

### ISSUE THREAD

**Issue by lukaschod** [barncastle/Battle.Net-Installer#4]
Getting error 2421 with command line execution:
BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "C:\D2R"

**Comment by lukaschod** [comment]
[Agent-20210416T124035.log](https://github.com/barncastle/Battle.Net-Installer/files/6325386/Agent-20210416T124035.log)

**Comment by lukaschod** [comment]
it was space, nvm

**Comment by barncastle** [comment]
Glad you sorted it, thanks for letting me know!
