### ISSUE TITLE
error when forgetting to install battle.net

### ISSUE THREAD

**Issue by jcageman** [barncastle/Battle.Net-Installer#6]
Thanks for this great tool! Just a small suggestion for improvement: it would be nice if a proper error is shown when battle.net has not been installed.

Current the error is as follows:
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

**Comment by barncastle** [comment]
Are you using version 1.4? The app should check before starting now as of #2 and https://github.com/barncastle/Battle.Net-Installer/commit/1c31777f6fe5bdc8c1f3212cf4f9b0bf74764989.

**Comment by jcageman** [comment]
I think i did install the latest, but can't test it now anymore, since i already installed BNetInstaller.exe, let's presume i installed the wrong version :) Thanks for the quick reply!

**Comment by barncastle** [comment]
Haha no problem :) Any other issues or suggestions, let me know.
