### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by n0vares** [barncastle/Battle.Net-Installer#7]
Hi Barncastle -

Thanks for this. Although *I* personally had zero problems with this and it works just as it should.... I've tried to help two people use this to install D2R and they received the error below. Do you have any insight into why? Thank you!

✔Installed proper runtimes
✔Tried cmd as admin and not as admin
✔Tried different folders, etc
✔Updated Bnet client + logged in recently

---------------------------------------------------------------------------------------------------

Microsoft Windows [Version 10.0.19041.928]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Users\Jim\Desktop\D2Res

C:\Users\Jim\Desktop\D2Res>BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "C:\D2R"
Authenticating
Queuing Install
Starting Install

Unhandled exception. System.Exception: Agent Error: 2421
 ---> System.Exception: {
  "error": 2421
}
   --- End of inner exception stack trace ---
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage response)
   at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
   at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)

C:\Users\Jim\Desktop\D2Res>

**Comment by barncastle** [comment]
I'm not at my pc at the moment but someone else had the same error code yesterday and it turned out to be disk space, see #4.

If that's not the issue, could you provide a log from one of these machines please? Iirc it is saved in %programdata%/battle.net/agent and then the agent subfolder with the highest number, thanks.

**Comment by n0vares** [comment]
Thank you! That's exactly what the problem was it turned out that he was trying to install it on a hard drive that didn't have enough room. 

Just in case anyone hasn't also told you but I had some issues with another person and that 2420 error (or whatever it was), and for him it turned out that he didn't even have the battle net client installed to begin with. After installing it it worked fine. So just in case you come across that error with anybody else tell them to make sure that the battlenet client is installed. 😅

Thank you for your reply!

**Comment by barncastle** [comment]
Brilliant, I'm glad you're all up and running now! Thanks for the info as well, its a great help as well.
If you or anyone has any other problems, feel free to create a new issue.
