### ISSUE TITLE
meet "2421" error

### ISSUE THREAD

**Issue by ClaudeFyre** [barncastle/Battle.Net-Installer#9]
hi, thanks for your job. I meet "2421"error but I do provide enough space(C disk 230G, D disk 350G), make right path(C:/Diablos, D:/Diablos). Could you please tell me what the error can be to my laptop? Thank you.

**Comment by barncastle** [comment]
Hi, apologies I was not home last weekend. Could you use [v1.5](https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.5) and copy the full error please? This version has more detailed logging.

**Comment by ClaudeFyre** [comment]
> Hi, apologies I was not home last weekend. Could you use [v1.5](https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.5) and copy the full error please? This version has more detailed logging.

Hi, thanks for your attention! I have tried the V1.5 and here is the error I met:
_Unhandled exception. System.Exception: Agent Error: 2421
 ---> System.Exception: {
  "error": 2421
}
   --- End of inner exception stack trace ---
   at BNetInstaller.Endpoints.BaseEndpoint.ValidateResponse(JToken response, String content)
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage response)
   at BNetInstaller.Endpoints.Repair.RepairEndpoint.Post()
   at BNetInstaller.Program.RepairProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)_
I am trying to install Diablo II: Resurrected and my laptop has 6300hq and 960m with enough space(C disk 230G, D disk 350G). I have tried administrator execution. Could you please give me some advise?

**Comment by barncastle** [comment]
Thank you. It looks like it it is trying to repair the game instead of installing it which is probably the issue. Are you using the command line or the interactive mode and what are you inputting?

Command line should be:
```
.\BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "C:\Diablos"
```

Interactive mode should be:
```
Please complete the following information:
TACT Product: osib
Agent UID: osi_beta
Installation Directory: C:\Diablos
Game/Asset Language: enus
Repair Install (Y/N): n
```

**Comment by Mutaracha** [comment]
on v.1.5 (on 1.4 work well)
Command - bnetinstaller.exe --prod osib --uid osi_beta --lang enUS --dir "F:\Games\D2R\"

Error in log
`Unhandled exception. System.Exception: Agent Error: Unable to install - 801.
 ---> System.Exception: {
  "form": {
    "authentication": {
      "error": 0
    },
    "eula": {
      "error": 0,
      "eula": true
    },
    "finalized": false,
    "game_dir": {
      "default": "C:\\Program Files\\",
      "dirname": "D2R Technical Alpha",
      "error": 801,
      **"game_dir": "C:/Program Files/D2R Technical Alpha",**
      "required_space": 21000000000,
      "required_space_info": {
        "size": 21000000000,
        "state": 1009
      },
      "warning": 806
    },
    "language": {
      "error": 704,
      "list": [
        "enUS"
      ],
      "speech": [
        "enUS"
      ],
      "text": [
        "enUS"
      ]
    },
    "min_spec": {
      "allow_arm_emulation": true,
      "error": 0,
      "required_cpu_speed": [
        0
      ],
      "required_os": "Windows 7",
      "required_ram": 0,
      "required_subversion": 0,
      "requires_64bit": true
    },
    "shortcut": "all",
    "tome_path": {
      "error": 0
    }
  },
  "response_uri": "/install/osi_beta"
}`

**Comment by barncastle** [comment]
@Mutaracha your error seems to be disk space related. The `game_dir` section is expecting 21gb of storage and is reporting an error code of `801` which is the same as #4. If you run 1.4 and it doesn't error could you let me know?

**Comment by Mutaracha** [comment]
> @Mutaracha your error seems to be disk space related. The `game_dir` section is expecting 21gb of storage and is reporting an error code of `801` which is the same as #4. If you run 1.4 and it doesn't error could you let me know?
the process checks the free space of the C: drive, must F: which is specified as --dir "F: \ Games \ D2R"

log from 1.4
bnetinstaller.exe --prod osib --uid osi_beta --lang enUS --dir "F:\Games\D2R"
Authenticating
Queuing Install
Starting Install

Downloading:        osib
Language:           enUS
Directory:          F:\Games\D2R\
Progress:           0,0000%

**Comment by barncastle** [comment]
>the process checks the free space of the C: drive, must F: which is specified as --dir "F: \ Games \ D2R"

I noticed that but it is something Battle.net is doing not this tool. Blizzard must check the default directory the first iteration for whatever reason.

I've updated the code to only check for global errors (how v1.4 worked) but have kept the extra details added in v1.5 and uploaded a [new release](https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.5.1). This may or may not fix the issue.

**Comment by Mutaracha** [comment]
> > the process checks the free space of the C: drive, must F: which is specified as --dir "F: \ Games \ D2R"
> 
> I noticed that but it is something Battle.net is doing not this tool. Blizzard must check the default directory the first iteration for whatever reason.
> 
> I've updated the code to only check for global errors (how v1.4 worked) but have kept the extra details added in v1.5 and uploaded a [new release](https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.5.1). This may or may not fix the issue.

1.5.1 bypasses my problem. Thank you!

**Comment by barncastle** [comment]
@Mutaracha Brilliant, thank you for the additional info you gave!
@ClaudeFyre This may possibly resolve your issue as well, let me know either way when you get a chance.

**Comment by barncastle** [comment]
Closing this as it has been a few months.
